spring:
  datasource:
    url: jdbc:mysql://localhost:3306/karting?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456