spring:
  profiles:
    active: dev
  datasource:
    initial-size: 10
    max-active: 20
    min-idle: 8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: vc.xji